from phe import paillier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

'''
Represents a Server that holds a trained ML model to classify emails

Code Inspired by the examples given in the Python Paillier Library github repository by
the creators of the cryptosystem
Source: https://github.com/data61/python-paillier/blob/master/examples/logistic_regression_encrypted_model.py
'''
class Server:

    # Initialize
    def __init__(self):
        self.ml_model = LinearSVC()

    # generates a random paillier public-private keypair for encryption
    def create_paillier_keypair(self):
        self.publickey, self.privatekey = paillier.generate_paillier_keypair()

    # returns the public-key that is stored
    def get_public_key(self):
        return self.publickey

    '''
    Fits the data to the machine learning model
    @param X - Vectorized text 
    @param y - Target variable (can be 0 - ham or 1 - spam)
    '''
    def fit(self, X, y):
        self.ml_model.fit(X, y)

    '''
    Predicts the value of target variable y for data X
    @param X - Vectorized text
    '''
    def predict(self, X):
        return self.ml_model.predict(X)

    '''
    Encrypts the coefficients of the trained ML model
    '''
    def encrypt_params(self):
        coefficients = self.ml_model.coef_[0,:]
        encrypted_weight = []
        for i in range(coefficients.shape[0]):
            encrypted_weight.append(self.publickey.encrypt(coefficients[i]))

        encrypted_intercept = self.publickey.encrypt(self.ml_model.intercept_[0])

        return encrypted_weight, encrypted_intercept

    '''
    Decrypts the scores generated by the Client using the private key
    @param scores - Encrypted score returned by the client
    @return Decrypted scores
    '''
    def decrypt_score(self, scores):
        output = []
        for element in scores:
            decrypted_score = self.privatekey.decrypt(element)
            threshold = 0.5
            if decrypted_score > threshold:
                output.append(1)
            else:
                output.append(0)

        return output